---
title: "Netherlands Bird Migration Map"
subtitle: "Based on weather radar measurements"
author: Bart Hoekstra
output: html_notebook
---

```{r setup, message=FALSE, warning=TRUE, include=FALSE}
library(tidyverse)
library(bioRad)
library(suncalc)
library(terra)
library(raster)
library(sf)
library(stars)
library(parallel)
library(ggdark)
```

# Download polar volume data from peak nights

```{r}
vp_mtr <- read_csv("data/vp_mtr_ordered_seasonal_day_night_migration.csv", 
                   col_types = cols(
                     date_trunc = col_datetime(),
                     odim_code = col_character(),
                     year_season = col_character(),
                     year = col_double(),
                     season = col_character(),
                     day_night = col_character(),
                     slope_max = col_double(),
                     slope_max_time = col_datetime(),
                     mtr = col_double(),
                     prop = col_double(),
                     mtr_cum = col_double(),
                     prop_cum = col_double(),
                     top = col_double()
                  )
                  )
```

```{r}
vp_mtr_cum50 <- vp_mtr %>%
  filter(prop_cum < 0.5 | (lag(prop_cum) < 0.5 & prop_cum >= 0.5))

vp_mtr_cum50
```

```{r}
calculate_scantime <- function(r) {
  if (r["odim_code"] == "nlhrw") {
    lat <- 51.8371
    lon <- 5.138
  }
  if (r["odim_code"] == "nldhl") {
    lat <- 52.9528
    lon <- 4.79061
  }
  
  if (r["day_night"] == "daylight") {
    scantime <- suncalc::getSunlightTimes(lat = lat, lon = lon, date = as.Date(r["date_trunc"]), keep = "sunrise")
    scantime <- scantime$sunrise + hours(2)
  }
  if (r["day_night"] == "night") {
    scantime <- suncalc::getSunlightTimes(lat = lat, lon = lon, date = as.Date(r["date_trunc"]) - 1, keep = "sunset")
    scantime <- scantime$sunset + hours(2) + minutes(30)
  }
  
  scantime <- round_date(scantime, "5 mins")
}

scantimes <- as_datetime(unlist(apply(vp_mtr_cum50, MARGIN = 1, FUN = calculate_scantime, simplify = FALSE)))

vp_mtr_cum50$moment <- scantimes
vp_mtr_cum50
```

```{r}
# minio/pvol/NL/HRW/2016/08/31/NLHRW_pvol_20160831T2350_6356.h5
dts <- dplyr::select(vp_mtr_cum50, odim_code, moment)

dts_hrw <- dts %>%
  filter(odim_code == "nlhrw") %>%
  pull(moment)

filepaths_hrw <- paste0("minio/pvol/NL/HRW/", year(dts_hrw), "/", sprintf("%02d", month(dts_hrw)), "/", sprintf("%02d", day(dts_hrw)), "/",
                        "NLHRW_pvol_", format(dts_hrw, format = "%Y%m%dT%H%M"), "_6356.h5")
filepaths_hrw_alt <- paste0("minio/pvol/NL/HRW/", year(dts_hrw), "/", sprintf("%02d", month(dts_hrw)), "/", sprintf("%02d", day(dts_hrw)), "/",
                        "NLHRW_pvol_", format(dts_hrw, format = "%Y%m%dT%H%M"), "_NL52.h5")
paths <- list(paste0("mc cp ", filepaths_hrw, " ."), paste0("mc cp ", filepaths_hrw_alt, " ."))

write_lines(unlist(paths), file = "data/pvol/hrw_files.sh", )

dts_dhl <- dts %>%
  filter(odim_code == "nldhl") %>%
  pull(moment)

filepaths_dhl <- paste0("minio/pvol/NL/DHL/", year(dts_dhl), "/", sprintf("%02d", month(dts_dhl)), "/", sprintf("%02d", day(dts_dhl)), "/",
                        "NLDHL_pvol_", format(dts_dhl, format = "%Y%m%dT%H%M"), "_6234.h5")
filepaths_dhl_alt <- paste0("minio/pvol/NL/DHL/", year(dts_dhl), "/", sprintf("%02d", month(dts_dhl)), "/", sprintf("%02d", day(dts_dhl)), "/",
                        "NLDHL_pvol_", format(dts_dhl, format = "%Y%m%dT%H%M"), "_NL51.h5")
paths <- list(paste0("mc cp ", filepaths_dhl, " ."), paste0("mc cp ", filepaths_dhl_alt, " ."))

write_lines(unlist(paths), file = "data/pvol/dhl_files.sh", )
```

```{r}
downloaded_files <- list.files("data/pvol", full.names = TRUE)
downloaded_files <- downloaded_files[!downloaded_files %in% c("data/pvol/dhl_files.sh", "data/pvol/hrw_files.sh")]
downloaded_files_hrw <- downloaded_files[str_detect(downloaded_files, "NLHRW")]
downloaded_files_dhl <- downloaded_files[str_detect(downloaded_files, "NLDHL")]

downloaded_files_dhl_dts <- as_datetime(unlist(
  lapply(downloaded_files_dhl, function(x) parse_date_time(str_split(x, "_")[[1]][3], "YmdHM"))))
downloaded_files_hrw_dts <- as_datetime(unlist(
  lapply(downloaded_files_hrw, function(x) parse_date_time(str_split(x, "_")[[1]][3], "YmdHM"))))

downloaded_dts_dhl <- data.frame(pvolfile = downloaded_files_dhl, moment = downloaded_files_dhl_dts)
downloaded_dts_dhl$odim_code <- "nldhl"
downloaded_dts_hrw <- data.frame(pvolfile = downloaded_files_hrw, moment = downloaded_files_hrw_dts)
downloaded_dts_hrw$odim_code <- "nlhrw"
downloaded_dts <- bind_rows(downloaded_dts_dhl, downloaded_dts_hrw)

vp_mtr_cum50 %>%
  left_join(downloaded_dts, by = join_by(odim_code == odim_code, moment == moment)) -> vp_mtr_cum50
```

# Process RBCs
This is done following the `pipeline.R` function.

# RBC Selection
Blablabla

# Selected usable scans

```{r}
accepted_files <- list.files("data/rbc_png/full/Accepted/")
rejected_files <- list.files("data/rbc_png/full/Rejected/")

rbc_file_from_png <- function(file, azim_method = "full") {
  f <- basename(file)
  ss <- str_split(f, "_")[[1]][1:4]
  radar <- str_to_lower(ss[1])
  moment <- parse_date_time(ss[3], "YmdHM")
  fp <- paste0("data/rbc/", str_c(ss, collapse = "_"), "_", azim_method, ".RDS")
  return(list("odim_code" = radar, "moment" = moment, "rbcfile" = fp))
}

accepted <- bind_rows(lapply(accepted_files, rbc_file_from_png)) %>% mutate(status = "Accepted")
rejected <- bind_rows(lapply(rejected_files, rbc_file_from_png)) %>% mutate(status = "Rejected")

classified_moments <- bind_rows(accepted, rejected)

vp_mtr_cum50 %>%
  left_join(classified_moments, by = join_by(odim_code, moment)) %>%
  mutate(status = replace_na(status, "Rejected")) %>%
  identity() -> vp_mtr_cum50_cl
```

# Process scans to stacks

```{r}
stack_rbcs <- function(rbcs, props, year_season, odimcode, daytime, threshold_max = 2500, mean_method = "pixels", overwrite = FALSE) {
  # See if files exist already
  daytime <- if_else(daytime == "night", "night", "day")
  filepath <- paste0("data/stacks/",
                     str_to_upper(odimcode), "_", year_season, "_thresh_", threshold_max, "_avg_", mean_method, "_", daytime, ".RDS")
  rasterpath <- paste0("data/stacks/",
                       str_to_upper(odimcode), "_", year_season, "_thresh_", threshold_max, "_avg_", mean_method, "_", daytime, ".tif")

  if (file.exists(filepath) && file.exists(rasterpath)) {
    if (!overwrite) {
      return("exists")
    }
  }

  r <- rbcs[[1]]
  rp <- r
  cs <- rbcs[[1]]$data@data$VIR
  cs <- cs * 0
  cp <- cs
  zeros <- cs

  VIRs <- list()
  css <- list()
  cps <- list()

  for(i in seq_along(rbcs)) {
    VIR <- rbcs[[i]]$data@data$VIR
    RAIN <- rbcs[[i]]$data@data$rain
    VIR[which(VIR > threshold_max)] <- NA
    VIR[which(VIR == 0)] <- NA
    VIR[which(RAIN > 0)] <- NA
    cs <- cs + 1 - (is.na(VIR) * 1)
    cp <- (1 * props[i]) - (is.na(VIR) * 1 * props[i])
    VIRs <- append(VIRs, list(VIR))
    css <- append(css, list(cs))
    cps <- append(cps, list(cp))
  }

  mVIR <- do.call(rbind, VIRs)
  mCSS <- do.call(rbind, css)
  mCPS <- do.call(rbind, cps)

  mVIR[is.na(mVIR)] <- 0
  VIR_summed <- mVIR[1, ] * 0

  for (j in seq_along(VIRs)) {
    if (j == 1) {
      VIR_summed <- as.vector(as.matrix(mVIR[1:j, ]))
      rp$data@data[paste0("VIR_", j)] <- VIR_summed
      next
    }
    
    if (mean_method == "scans") {
      VIR_summed <- colSums(as.matrix(mVIR[1:j, ])) / j
    } else if (mean_method == "pixels") {
      VIR_summed <- colSums(as.matrix(mVIR[1:j, ])) / css[[j]]
    } else if (mean_method == "weighted") {
      VIR_summed <- colSums(as.matrix(mVIR[1:j, ]) * as.matrix(mCPS[1:j, ])) / colSums(as.matrix(mCPS[1:j, ]))
    } else if (mean_method == "weighted_scans") {
      VIR_summed <- colSums(sweep(as.matrix(mVIR[1:j, ]), MARGIN = 1, props[1:j], `*`)) / sum(props[1:j])
    }
    rp$data@data[paste0("VIR_", j)] <- as.numeric(VIR_summed)
  }

  remove_variables <- c("VID", "R", "overlap", "eta_sum", "eta_sum_expected", "rain")
  for (var in remove_variables) {
    rp$data@data[var] <- NULL
  }
  rp$data$css <- as.vector(css[[length(css)]])
  rp$data$VIR <- as.vector(as.matrix(rp$data@data[paste0("VIR_", length(VIRs))]))

  rp <- calculate_param(rp, VIR_log10 = log10(VIR), VIR_log = log(VIR), VIR_sqrt = sqrt(VIR))
  saveRDS(rp, filepath)
  rrast <- terra::rast(rp$data)
  fixedlayers <- c("VIR", "css", "cps", "VIR_log10", "VIR_log", "VIR_sqrt")
  layernames <- names(rrast)
  layerorder <- c(which(layernames %in% fixedlayers), which(!layernames %in% fixedlayers))
  rrast <- subset(rrast, layerorder)
  terra::writeRaster(rrast, rasterpath, overwrite = overwrite)
}

g <- expand.grid(year_season = unique(vp_mtr_cum50_cl$year_season),
                 day_night = unique(vp_mtr_cum50_cl$day_night),
                 odim_code = unique(vp_mtr_cum50_cl$odim_code))

generate_stacks <- function(year_season, day_night, odim_code,
                            th = c(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000),
                            mm = c("pixels", "scans", "weighted", "weighted_scans"),
                            overwrite = FALSE) {
  
  vp_mtr_cum50_cl %>%
    filter(status == "Accepted", year_season == !!year_season, day_night == !!day_night, odim_code == !!odim_code) %>%
    drop_na() %>%
    arrange(top) %>%
    dplyr::select(rbcfile, prop) -> files
  
  if (nrow(files) == 0) return("files do not exist")
  
  gr <- expand.grid(th = th, mm = mm, stringsAsFactors = FALSE)
  gr <- asplit(gr, 1)
  
  rbcs <- lapply(files$rbcfile, readRDS)
  lapply(gr, function(x) {stack_rbcs(rbcs = rbcs, props = files$prop, year_season = year_season, daytime = day_night, odimcode = odim_code, 
                                     threshold_max = as.numeric(x["th"]), mean_method = x["mm"], overwrite = overwrite)})
}

processing_stacking <- mcmapply(generate_stacks, year_season = g$year_season, day_night = g$day_night, odim_code = g$odim_code,
                                overwrite = FALSE, mc.cores = 6, mc.preschedule = FALSE)
# processing_stacking <- mapply(generate_stacks, year_season = g$year_season, day_night = g$day_night, odim_code = g$odim_code)
saveRDS(processing_stacking, paste0("data/logs/processing_stacking_", format(Sys.time(), "%Y%m%dT%H%M"), ".RDS"))
```

# Combine season stacks to radar, time stacks

```{r}
final_stacks <- expand.grid(odim_code = c("NLHRW", "NLDHL"),
                            season = c("spring", "autumn"),
                            daytime = c("day", "night"),
                            th = c(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000),
                            mm = c("pixels", "scans", "weighted_scans", "weighted"))

for (i in 1:nrow(final_stacks)) {
  fs <- final_stacks[i, ]
  # rastfiles <- Sys.glob(paste0("data/stacks/", fs$odim_code, "_*_", fs$season, "_", fs$daytime, ".tif"))
  rastfiles <- Sys.glob(
    paste0("data/stacks/", str_to_upper(fs$odim_code), "_*_", fs$season, "_thresh_", fs$th, "_avg_", fs$mm, "_", fs$daytime, ".tif")
  )
  # Store every 1st layer
  # layer_ids <- seq(from = 1, by = 10, length.out = length(rastfiles))
  
  stk <- terra::rast(lapply(rastfiles, function(x) {
    tryCatch(terra::rast(x, lyrs = "VIR"), 
             error = function(err) {
               print(err)
             })
  }))
  # stk <- terra::rast(rastfiles, lyrs = "VIR")
  rmean <- app(stk, mean)
  file_out <- paste0("data/final_stacks/", fs$odim_code, "_", fs$season, "_thresh_", fs$th, "_avg_", fs$mm, "_", fs$daytime, ".tif")
  
  if (fs$odim_code == "NLHRW") {
    lat <- 51.8371
    lon <- 5.138
  }
  if (fs$odim_code == "NLDHL") {
    lat <- 52.9528
    lon <- 4.79061
  }
  
  circle_radius <- 100000  # 100 km in meters

  # Create a simple features (sf) point object
  center_point <- st_sfc(st_point(c(lon, lat)))
  
  # Buffer the point to create a circular polygon
  st_crs(center_point) <- 4326
  center_point <- st_transform(center_point, crs = st_crs(rmean))
  circle <- st_buffer(center_point, dist = circle_radius)
  # mask(x = raster_data, mask = circle)  
  masked_raster <- st_rasterize(st_as_sf(circle), st_as_stars(st_bbox(rmean, values = NA_real_), nx = 640, ny = 640))
  masked_raster[masked_raster == 0] <- NA
  
  raster_masked <- terra::mask(rmean, as(masked_raster, "SpatRaster"))
  
  writeRaster(raster_masked, file_out, overwrite = TRUE)
}
```

# Combine radar, time stacks to national-level maps

```{r}
final_stacks <- expand.grid(season = c("spring", "autumn"),
                            daytime = c("day", "night"),
                            th = c(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000),
                            mm = c("pixels", "scans", "weighted_scans", "weighted"),
                            zmax = c(500, 600, 700, 800, 900, 1000, 1500, 2000))

fstacks <- asplit(final_stacks, 1)
  
save_map <- function(x) {
  fs <- x
  fstacks <- paste0("data/final_stacks/", c("NLHRW", "NLDHL"), "_", 
                    fs["season"], "_thresh_", fs["th"], "_avg_", fs["mm"], "_", fs["daytime"], ".tif")
  fstacks <- str_replace_all(fstacks, " ", "")
  mapfile <- paste0("data/maps/NL_", fs["season"], "_", fs["daytime"], "_thresh_", fs["th"], "_avg_", fs["mm"], ".tif")
  mapfile <- str_replace_all(mapfile, " ", "")
  if (fs["mm"] == "weighted") {
    fsmm <- "weighted_pixels"
  } else {
    fsmm <- fs["mm"]
  }
  mapfile_plot <- paste0("data/maps_plots/VIR_", fs["zmax"], "/", fs["daytime"], "/", fsmm, "/NL_", 
                         fs["season"], "_", fs["daytime"], "_thresh_", fs["th"], "_avg_", fsmm, ".png")
  mapfile_plot <- str_replace_all(mapfile_plot, " ", "")
  
  r1 <- rast(fstacks[1]) %>% project("EPSG:28992")
  r2 <- rast(fstacks[2]) %>% project("EPSG:28992")
  
  bbox1 <- ext(r1)
  bbox2 <- ext(r2)
  
  combined_bbox <- c(min(bbox1$xmin, bbox2$xmin), max(bbox1$xmax, bbox2$xmax), min(bbox1$ymin, bbox2$ymin), max(bbox1$ymax, bbox2$ymax))
  
  rn <- rast(ext = combined_bbox, crs = "EPSG:28992")
  res(rn) <- 500
  
  r1_resampled <- resample(r1, rn)
  r2_resampled <- resample(r2, rn)
  
  m <- mosaic(sprc(r1_resampled, r2_resampled), fun = max)
  writeRaster(m, mapfile, overwrite = TRUE)
  
  data <- raster::as.data.frame(m, xy = TRUE)
  
  c <- crs(m)
  nl <- geojsonsf::geojson_sfc("data/gis/Netherlands.geojson") %>% st_transform(c)
  nhol <- geojsonsf::geojson_sfc("data/gis/Noord-Holland.geojson") %>% st_transform(c)
  nhol_buf <- geojsonsf::geojson_sfc("data/gis/Noord-Holland-10km-Buffer.geojson") %>% st_transform(c)
  radar_buf <- geojsonsf::geojson_sf("data/gis/Radars-100km-Buffer.geojson") %>% st_transform(c)
  
  radar_bbox <- st_bbox(radar_buf)
  
  padding <- 500
  # xlim <- c(min(data$x), max(data$x))
  xlim <- c(radar_bbox$xmin - padding, radar_bbox$xmax + padding)
  # ylim <- c(min(data$y), max(data$y))
  ylim <- c(radar_bbox$ymin - padding, radar_bbox$ymax + padding)
  zlim <- c(0, quantile(data$mean, 0.95))
  zlim <- c(0, as.numeric(fs["zmax"]))
  season <- if_else(fs["daytime"] == "night", "by Night", "by Day")
  title <- paste0(str_to_sentence(fs["season"]), " ", season)
  subtitle <- paste0("Noise threshold: ", fs["th"], " / Stacking method: ", fsmm)
  
  ggplot(data) +
    geom_tile(aes(x = x, y = y, fill = mean)) +
    scale_fill_viridis_c(limits = zlim, name = "Mean\nVIR", oob = scales::squish, option = "inferno") +
    geom_sf(data = nl, fill = "NA", color = "white", linewidth = .3) +
    geom_sf(data = nhol_buf, fill = "NA", color = "white", linewidth = .3) +
    geom_sf(data = nhol, fill = "NA", color = "white", linewidth = .3) +
    geom_sf(data = radar_buf, fill = "NA", color = "#ffffffaa", linewidth = .3) +
    # geom_sf(data = radar_buf, fill = "NA", color = alpha("#ffffff", 0.5), linewidth = .3) +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    ggtitle(title, subtitle) +
    # ggtitle(title) +
    dark_theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title = element_text(size = 14),
          plot.subtitle = element_text(size = 10),
          plot.background = element_rect(color = "black", fill = "black", linewidth = 6),
          legend.position = c(1.02, 0.66),
          plot.margin = unit(c(1,1,1,1), "cm")) -> pl1
  
  ggsave(mapfile_plot, plot = pl1, width = 5, height = 6)
}

processing <- mclapply(fstacks, save_map, mc.cores = 10, mc.preschedule = FALSE)

saveRDS(processing, paste0("data/logs/processing_mapping_", format(Sys.time(), "%Y%m%dT%H%M"), ".RDS"))
```

# Visualisations

```{r, fig.width=6, fig.height=5}
mask_raster <- function(r, odimcode) {
  if (odimcode == "NLHRW") {
    lat <- 51.8371
    lon <- 5.138
  }
  if (odimcode == "NLDHL") {
    lat <- 52.9528
    lon <- 4.79061
  }
  
  circle_radius <- 100000  # 100 km in meters
  
  # Create a simple features (sf) point object
  center_point <- st_sfc(st_point(c(lon, lat)))
  
  # Buffer the point to create a circular polygon
  st_crs(center_point) <- 4326
  center_point <- st_transform(center_point, crs = st_crs(r))
  circle <- st_buffer(center_point, dist = circle_radius)
  masked_raster <- st_rasterize(st_as_sf(circle), st_as_stars(st_bbox(r, values = NA_real_), nx = 640, ny = 640))
  masked_raster[masked_raster == 0] <- NA
  
  raster_masked <- terra::mask(r, as(masked_raster, "SpatRaster"))
  return(raster_masked)
}

odimcode <- "NLHRW"
r <- rast("data/stacks/NLHRW_2022_autumn_thresh_5000_avg_weighted_scans_day.tif") %>% mask_raster(odimcode)
c <- crs(r)
nl <- geojsonsf::geojson_sfc("data/gis/Netherlands.geojson") %>% st_transform(c)
if (odimcode == "NLHRW") {
  radar_buf <- geojsonsf::geojson_sf("data/gis/Radars-100km-Buffer.geojson") %>% st_transform(c) %>% filter(fid == 2)  
} else {
  radar_buf <- geojsonsf::geojson_sf("data/gis/Radars-100km-Buffer.geojson") %>% st_transform(c) %>% filter(fid == 1)
}
radar_bbox <- st_bbox(radar_buf)


r %>%
  as.data.frame(xy = TRUE) %>%
  dplyr::select(x, y, starts_with("VIR_"), -c(VIR_log10, VIR_log, VIR_sqrt)) %>%
  pivot_longer(cols = starts_with("VIR_"), names_to = "scan", values_to = "VIR") %>%
  mutate(scan = str_replace(scan, "VIR_", ""),
         VIR = replace_na(VIR, 0)) %>%
  identity() -> rdf

for (sc in unique(rdf$scan)) {
  rdf %>%
    filter(scan == sc) -> rd
  
  ggplot() +
    geom_tile(data = rd, aes(x = x, y = y, fill = VIR)) +
    geom_sf(data = nl, fill = "NA", color = "white", linewidth = .3) +
    geom_sf(data = st_difference(nl, radar_buf), fill = alpha("black", .99), color = alpha("black", .5), linewidth = 4) +
    geom_sf(data = radar_buf, color = "white", fill = "NA", linewidth = .3) +
    coord_sf(xlim = c(radar_bbox$xmin, radar_bbox$xmax), ylim = c(radar_bbox$ymin, radar_bbox$ymax + 40000)) +
    scale_fill_viridis_c(option = "inferno", limits = c(0, 1000), oob = scales::squish) +
    dark_theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.background = element_rect(color = "black", fill = "black", size = 6),
          # legend.position = "bottom",
          legend.position = c(0.9, 0.1),
          legend.title = element_text(vjust = 0.1)) +
    annotate("text", x = min(rd$x), y = max(rd$y) + 40000, label = "Autumn 2022", hjust = 0, size = 6) +
    annotate("text", x = min(rd$x), y = max(rd$y) + 25000, label = "by night", hjust = 0, size = 5) +
    annotate("text", x = max(rd$x), y = max(rd$y) + 40000, label = "Scans in stack", hjust = 1, size = 6) +
    annotate("text", x = max(rd$x) + 2500, y = max(rd$y) + 20000, label = paste0(sc), hjust = 1, size = 12) +
    guides(fill = guide_colorbar(title.position = "left"))
  
  ggsave(paste0("data/stacks_gifs/NLHRW_2022_", sc, ".png"), width = 6, height = 7)
}
# ffmpeg -framerate 1 -pattern_type glob -i '*.png' -c:v libx264 -r 30 -pix_fmt yuv420p output.mp4
```

```{r}
# vp_mtr_cum50_cl %>%
#   filter(status == "Accepted") %>%
#   group_by(year, season, odim_code, day_night) %>%
#   summarise(total_prop = sum(prop)) %>%
#   mutate(season_date = case_when(
#     season == "spring" ~ as.Date(paste(year, "03-15", sep = "-")),
#     season == "autumn" ~ as.Date(paste(year, "09-15", sep = "-")),
#     TRUE ~ NA_Date_)) -> sp

vp_mtr_cum50_cl %>%
  filter(status == "Accepted") %>%
  group_by(year, season, odim_code, day_night) %>%
  summarise(total_prop = sum(prop)) %>%
  mutate(season_date = case_when(
    season == "spring" ~ as.Date(paste(year, "03-15", sep = "-")),
    season == "autumn" ~ as.Date(paste(year, "09-15", sep = "-")),
    TRUE ~ NA_Date_),
    odim_code = case_when(
      odim_code == "nlhrw" ~ "Herwijnen",
      odim_code == "nldhl" ~ "Den Helder"
    ),
    day_night = case_when(
      day_night == "daylight" ~ "Day",
      day_night == "night" ~ "Night"
    )) -> sp

sp

sp %>%
  group_by(odim_code, day_night) %>%
  summarise(mean_prop = mean(total_prop)) -> sp_means

sp_means
```



```{r}
# Define the moon and sun symbols using Unicode
ggplot(sp) +
  geom_point(aes(x = season_date, y = total_prop, color = day_night, shape = day_night, fill = day_night), size = 3) +
  dark_theme_gray(base_size = 14) +
  geom_hline(data = sp_means, aes(yintercept = mean_prop, color = day_night), linetype = "dashed") +
  scale_color_manual(values = c("yellow", "white")) +
  scale_fill_manual(values = c("yellow", "white")) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  scale_y_continuous(labels = scales::label_percent()) +
  scale_shape_manual(values = c(24, 25)) +
  facet_wrap(vars(odim_code)) +
  xlab("Season") +
  ylab("% of migration mapped") + 
  labs(title = "Seasonal proportion of migration included in map", 
       # subtitle = "After removal of unsuitable scans",
       color = "Time of day", shape = "Time of day", fill = "Time of day") +
  theme(plot.background = element_rect(color = "black", fill = "black", size = 6))

ggsave("seasonal_props.pdf", width = 10, height = 6)
```


